sudo: false
language: node_js
node_js:
  - 0.10

env:
  matrix:
    - BROWSER=chrome  BVER=stable

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=unstable
    
before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
  
addons:
  sauce_connect:
    username: "vyvanand"
    access_key: "d4d8d634-a6ee-493f-a42b-97f0fd54c813"
    direct_domains: github.com

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done

